#ifndef ULDFILTERPROJECT_GLOBAL_H
#define ULDFILTERPROJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ULDFILTERPROJECT_LIBRARY)
#  define ULDFILTERPROJECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ULDFILTERPROJECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ULDFILTERPROJECT_GLOBAL_H
